language: android

# Permission bugfix form Travis CI
before_install:
 - chmod +x gradlew

android:
 components:
 - tools
 - platform-tools
 - build-tools-27.0.3
 - android-27

licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+